"use client";

import React, { useState } from "react";
import {
  ContractAnalysisResult,
  DeadlineObligation,
} from "@/lib/types";
import {
  Briefcase,
  Calendar,
  HelpCircle,
  Download,
  Copy,
  Check,
  CheckCircle2,
  Clock,
  AlertCircle,
  FileCheck,
} from "lucide-react";

interface LawyerDossierProps {
  analysis: ContractAnalysisResult;
}

export default function LawyerDossier({ analysis }: LawyerDossierProps) {
  const [deadlines, setDeadlines] = useState<DeadlineObligation[]>(
    analysis.deadlines || []
  );
  const [copiedDossier, setCopiedDossier] = useState(false);

  const toggleStatus = (id: string) => {
    setDeadlines((prev) =>
      prev.map((d) => {
        if (d.id === id) {
          const nextStatus =
            d.status === "Pending"
              ? "Completed"
              : d.status === "Completed"
              ? "Flagged"
              : "Pending";
          return { ...d, status: nextStatus };
        }
        return d;
      })
    );
  };

  const generateMarkdownDossier = () => {
    return `# Legal Consultation Briefing Dossier
Generated by LexiGuard AI for: ${analysis.documentTitle}
Date: ${new Date().toLocaleDateString()}
Contract Type: ${analysis.contractType}
Identified Parties: ${analysis.keyParties.join(", ")}
Overall Calculated Risk Score: ${analysis.overallRiskScore}/100 (${analysis.overallRiskRating})

---

## 1. Executive Summary
${analysis.executiveSummary}

---

## 2. Top Critical & High Risk Clauses
${analysis.clauses
  .filter((c) => c.riskLevel === "Critical" || c.riskLevel === "High")
  .map(
    (c) => `
### ${c.clauseNumber}: ${c.title} [Risk: ${c.riskLevel} - ${c.riskScore}/100]
- **Original Excerpt**: "${c.originalText}"
- **Plain English**: ${c.plainEnglish}
- **Vulnerability / The Trap**: ${c.theTrap}
- **Target Commercial Benchmark**: ${c.standardBenchmark}
`
  )
  .join("\n")}

---

## 3. Missing Protective Clauses (Omission Radar)
${
  analysis.missingClauses && analysis.missingClauses.length > 0
    ? analysis.missingClauses
        .map(
          (m) => `
- **${m.clauseName}** (${m.importance} Priority)
  - Why Needed: ${m.whyNeeded}
  - Suggested Request: "${m.recommendedAddition}"
`
        )
        .join("\n")
    : "None detected."
}

---

## 4. Key Deadlines & Temporal Obligations
${deadlines
  .map(
    (d) => `
- [${d.status}] **${d.title}**: ${d.timeframe} (Responsible: ${d.responsibleParty})
  - Consequence of Non-Compliance: ${d.consequenceOfBreach}
`
  )
  .join("\n")}

---

## 5. Five Prepared Questions for Legal Counsel
${analysis.lawyerQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}

---
*Notice: This briefing dossier was generated by LexiGuard AI for informational and preparation purposes to reduce consultation time with a licensed attorney. It does not constitute formal legal advice.*
`;
  };

  const handleCopyDossier = () => {
    navigator.clipboard.writeText(generateMarkdownDossier());
    setCopiedDossier(true);
    setTimeout(() => setCopiedDossier(false), 2000);
  };

  const handleDownload = () => {
    const md = generateMarkdownDossier();
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute(
      "download",
      `Lawyer_Briefing_Dossier_${analysis.contractType.replace(/\s+/g, "_")}.md`
    );
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      {/* Dossier Header */}
      <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 shadow-xl space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-3 border-b border-gray-800 gap-3">
          <div>
            <h2 className="text-base font-semibold text-white flex items-center space-x-2">
              <Briefcase className="w-5 h-5 text-amber-400" />
              <span>Lawyer Briefing Pack &amp; Timeline Checklist</span>
            </h2>
            <p className="text-xs text-gray-400 mt-0.5">
              Turn complex contract analysis into a structured consultation pack to save $250–$650/hr in billable attorney fees.
            </p>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopyDossier}
              className="px-3 py-1.5 text-xs bg-gray-800 hover:bg-gray-700 text-gray-200 border border-gray-700 rounded-md flex items-center space-x-1.5 transition-colors"
            >
              {copiedDossier ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Copied Dossier</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy Markdown</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownload}
              className="px-3 py-1.5 text-xs bg-amber-600 hover:bg-amber-500 text-white font-medium rounded-md flex items-center space-x-1.5 transition-colors shadow-md shadow-amber-600/20"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Dossier (.md)</span>
            </button>
          </div>
        </div>

        {/* Section 1: Timeline & Obligation Checklist */}
        <div className="space-y-3 pt-1">
          <div className="flex items-center space-x-2 text-sm font-bold text-white uppercase tracking-wider">
            <Calendar className="w-4 h-4 text-blue-400" />
            <span>Obligation &amp; Deadline Checklist ({deadlines.length})</span>
          </div>

          <div className="space-y-2">
            {deadlines.map((dl) => (
              <div
                key={dl.id}
                onClick={() => toggleStatus(dl.id)}
                className={`p-3.5 rounded-lg border cursor-pointer transition-all flex items-start justify-between gap-3 ${
                  dl.status === "Completed"
                    ? "bg-gray-950/60 border-emerald-900/40 text-gray-400"
                    : dl.status === "Flagged"
                    ? "bg-rose-950/30 border-rose-800/60 text-gray-200"
                    : "bg-gray-950 border-gray-800 text-gray-200"
                }`}
              >
                <div className="flex items-start space-x-3">
                  <div className="mt-0.5">
                    {dl.status === "Completed" ? (
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    ) : dl.status === "Flagged" ? (
                      <AlertCircle className="w-4 h-4 text-rose-400" />
                    ) : (
                      <Clock className="w-4 h-4 text-gray-500" />
                    )}
                  </div>
                  <div>
                    <div className="flex items-center space-x-2">
                      <span
                        className={`text-xs font-semibold ${
                          dl.status === "Completed" ? "line-through text-gray-500" : "text-white"
                        }`}
                      >
                        {dl.title}
                      </span>
                      <span className="text-[10px] bg-gray-900 border border-gray-800 text-gray-400 px-1.5 py-0.2 rounded font-mono">
                        Party: {dl.responsibleParty}
                      </span>
                    </div>
                    <p className="text-xs text-gray-400 mt-0.5">
                      <strong className="text-gray-300">Timeframe:</strong> {dl.timeframe} •{" "}
                      <strong className="text-gray-300">Risk on Breach:</strong>{" "}
                      {dl.consequenceOfBreach}
                    </p>
                  </div>
                </div>

                <span
                  className={`text-[10px] px-2 py-0.5 rounded font-mono font-semibold flex-shrink-0 ${
                    dl.status === "Completed"
                      ? "bg-emerald-950 text-emerald-300 border border-emerald-800"
                      : dl.status === "Flagged"
                      ? "bg-rose-950 text-rose-300 border border-rose-800"
                      : "bg-gray-800 text-gray-400"
                  }`}
                >
                  {dl.status} (Click to toggle)
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Section 2: Top 5 Questions Prepared for Legal Counsel */}
        <div className="space-y-3 pt-4 border-t border-gray-800">
          <div className="flex items-center space-x-2 text-sm font-bold text-white uppercase tracking-wider">
            <HelpCircle className="w-4 h-4 text-amber-400" />
            <span>5 Sharp Questions to Ask a Lawyer During Consultation</span>
          </div>
          <p className="text-xs text-gray-400">
            Hand these targeted questions directly to your attorney or legal clinic to maximize your 15-to-30-minute consultation window:
          </p>

          <div className="space-y-2">
            {analysis.lawyerQuestions.map((question, i) => (
              <div
                key={i}
                className="bg-gray-950 border border-amber-900/30 rounded-lg p-3 flex items-start space-x-3 text-xs text-gray-200"
              >
                <span className="bg-amber-950 text-amber-300 font-bold px-2 py-0.5 rounded border border-amber-800/60 font-mono text-[11px] flex-shrink-0">
                  Q{i + 1}
                </span>
                <p className="leading-relaxed">{question}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Informational Reminder Footer */}
        <div className="bg-gray-950/60 border border-gray-800 rounded-lg p-3 text-[11px] text-gray-400 flex items-center space-x-2">
          <FileCheck className="w-4 h-4 text-blue-400 flex-shrink-0" />
          <span>
            This dossier organizes your facts, identified clauses, and prioritized questions. Handing this to a licensed attorney ensures they focus immediately on high-risk clauses rather than reading boilerplate at hourly rates.
          </span>
        </div>
      </div>
    </div>
  );
}
